In [1]:
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('ggplot')

In [2]:
df = pd.read_excel("geral.xlsx", engine='openpyxl')

In [3]:
df["Parametro"].value_counts().head()

Carbono Orgânico Total    21
pH                        21
Nitrogênio-Nitrito        21
Fluoreto Total            21
Sulfato Total             21
Name: Parametro, dtype: int64

In [4]:
df[df["Parametro"] == "DBO (5, 20)"]["Unidade"]

380    mg/L
381    mg/L
382    mg/L
383    mg/L
384    mg/L
385    mg/L
386    mg/L
387    mg/L
388    mg/L
389    mg/L
390    mg/L
391    mg/L
392    mg/L
393    mg/L
394    mg/L
395    mg/L
396    mg/L
397    mg/L
398    mg/L
399    mg/L
400    mg/L
Name: Unidade, dtype: object

In [5]:
w_pH = 0.12
w_DBO = 0.10
w_OD = 0.17
w_temp = 0.10
w_nitro = 0.10
w_turb = 0.08
w_fos = 0.1
w_res = 0.08
w_fosf = 0.1
w_coli = 0.15

___
#### Reading Data

In [6]:
dbo = pd.read_excel("dbo.xlsx", engine='openpyxl')
turbidez = pd.read_excel("turbidez.xlsx", engine='openpyxl')
nitrogenio = pd.read_excel("nitrogenio.xlsx", engine='openpyxl')
oxigenio = pd.read_excel("oxigenio.xlsx", engine='openpyxl')
ph = pd.read_excel("ph.xlsx", engine='openpyxl')
temperatura = pd.read_excel("temperatura.xlsx", engine='openpyxl')
fosforo = pd.read_excel("fosforo.xlsx", engine='openpyxl')
residuos = pd.read_excel("residuos.xlsx", engine='openpyxl')
ecolif = pd.read_excel("ecoliformes.xlsx", engine='openpyxl')

In [7]:
coliformes = pd.DataFrame()
coliformes["Valor"] = ecolif["Valor"]*1.25

In [8]:
_data = pd.DataFrame()
_data["DBO"] = dbo["Valor"]
_data["Oxigenio"] = oxigenio["Valor"]
_data["Nitrogenio"] = nitrogenio["Valor"]
_data["Fosforo"] = fosforo["Valor"]
_data["Temperatura"] = temperatura["Valor"]
_data["Residuos"] = residuos["Valor"]
_data["pH"] = ph["Valor"]
_data["Turbidez"] = turbidez["Valor"]
_data["Coliformes"] = coliformes["Valor"]
_data = _data.set_index(pd.to_datetime(dbo["Data Coleta"].values))
_data

,DBO,Oxigenio,Nitrogenio,Fosforo,Temperatura,Residuos,pH,Turbidez,Coliformes
2017-03-01,2.0,4.70,0.18,0.05,29.7,58.0,6.50,13.0,230.00
2017-02-03,2.0,4.70,0.25,0.05,27.9,54.0,6.83,14.0,250.00
2017-05-18,2.0,6.50,0.25,0.03,19.5,86.0,6.92,11.0,650.00
2017-06-07,2.0,8.80,0.44,0.02,17.5,70.0,7.08,13.0,140.00
2017-09-14,2.0,6.80,0.14,0.02,21.5,50.0,7.05,8.0,140.00
2017-11-16,2.0,5.60,0.13,0.05,28.8,50.0,6.92,15.0,170.00
2018-11-01,2.0,5.30,0.41,0.07,23.6,85.0,7.09,35.0,255.00
2018-06-03,2.0,4.50,0.18,0.07,26.2,72.0,7.40,26.0,750.00
2018-03-05,2.0,5.80,0.24,0.04,26.1,68.0,6.34,9.2,108.75
2018-12-07,2.0,6.30,0.22,0.03,20.0,50.0,6.48,8.8,50.00
2018-09-18,2.0,4.90,0.11,1.80,21.5,77.0,6.90,25.0,500.00
2018-11-22,2.0,5.30,0.17,0.08,25.0,80.0,6.79,40.0,220.00
2019-10-01,2.0,4.79,0.18,0.07,29.8,54.0,6.83,45.0,550.00
2019-03-14,2.0,5.56,0.17,0.07,28.6,58.0,6.81,19.0,850.00
2019-05-28,2.0,6.27,0.08,0.03,19.4,51.0,6.41,6.6,575.00
2019-07-25,2.0,7.40,0.36,0.03,18.6,63.0,6.56,11.0,98.75
2019-12-09,2.0,4.20,0.20,0.04,21.2,56.0,6.85,21.0,108.75
2019-11-18,2.0,7.10,0.20,0.13,23.3,110.0,6.89,75.0,360.00
2020-10-03,2.0,7.30,0.35,0.06,24.5,50.0,6.69,16.0,175.00
2020-11-17,5.0,8.70,0.18,0.10,31.4,50.0,7.20,24.0,975.00
2020-12-17,3.0,7.00,0.14,0.06,30.6,50.0,7.00,24.0,2750.00

___
#### Ploting Data

In [13]:
# plt.figure(figsize=(20,7))
# plt.plot(_data.index, _data["DBO"], "bo", markersize=10)
# plt.title("DBO")
# plt.grid(True)
# plt.show()

# plt.figure(figsize=(20,7))
# plt.plot(_data.index, _data["Oxigenio"], "bo", markersize=10)
# plt.title("Oxigenio")
# plt.grid(True)
# plt.show()

# plt.figure(figsize=(20,7))
# plt.plot(_data.index, _data["Nitrogenio"], "bo", markersize=10)
# plt.title("Nitrogenio")
# plt.grid(True)
# plt.show()

# plt.figure(figsize=(20,7))
# plt.plot(_data.index, _data["Residuos"], "bo", markersize=10)
# plt.title("Residuos")
# plt.grid(True)
# plt.show()

# plt.figure(figsize=(20,7))
# plt.plot(_data.index, _data["Temperatura"], "bo", markersize=10)
# plt.title("Temperatura")
# plt.grid(True)
# plt.show()

# plt.figure(figsize=(20,7))
# plt.plot(_data.index, _data["pH"], "bo", markersize=10)
# plt.title("pH")
# plt.grid(True)
# plt.show()

# plt.figure(figsize=(20,7))
# plt.plot(_data.index, _data["Fosforo"], "bo", markersize=10)
# plt.title("Fosforo")
# plt.grid(True)
# plt.show()

# plt.figure(figsize=(20,7))
# plt.plot(_data.index, _data["Turbidez"], "bo", markersize=10)
# plt.title("Turbidez")
# plt.grid(True)
# plt.show()

# plt.figure(figsize=(20,7))
# plt.plot(_data.index, _data["Coliformes"], "bo", markersize=10)
# plt.title("Coliformes")
# plt.grid(True)
# plt.show()

In [10]:
_data

,DBO,Oxigenio,Nitrogenio,Fosforo,Temperatura,Residuos,pH,Turbidez,Coliformes
2017-03-01,2.0,4.70,0.18,0.05,29.7,58.0,6.50,13.0,230.00
2017-02-03,2.0,4.70,0.25,0.05,27.9,54.0,6.83,14.0,250.00
2017-05-18,2.0,6.50,0.25,0.03,19.5,86.0,6.92,11.0,650.00
2017-06-07,2.0,8.80,0.44,0.02,17.5,70.0,7.08,13.0,140.00
2017-09-14,2.0,6.80,0.14,0.02,21.5,50.0,7.05,8.0,140.00
2017-11-16,2.0,5.60,0.13,0.05,28.8,50.0,6.92,15.0,170.00
2018-11-01,2.0,5.30,0.41,0.07,23.6,85.0,7.09,35.0,255.00
2018-06-03,2.0,4.50,0.18,0.07,26.2,72.0,7.40,26.0,750.00
2018-03-05,2.0,5.80,0.24,0.04,26.1,68.0,6.34,9.2,108.75
2018-12-07,2.0,6.30,0.22,0.03,20.0,50.0,6.48,8.8,50.00
2018-09-18,2.0,4.90,0.11,1.80,21.5,77.0,6.90,25.0,500.00
2018-11-22,2.0,5.30,0.17,0.08,25.0,80.0,6.79,40.0,220.00
2019-10-01,2.0,4.79,0.18,0.07,29.8,54.0,6.83,45.0,550.00
2019-03-14,2.0,5.56,0.17,0.07,28.6,58.0,6.81,19.0,850.00
2019-05-28,2.0,6.27,0.08,0.03,19.4,51.0,6.41,6.6,575.00
2019-07-25,2.0,7.40,0.36,0.03,18.6,63.0,6.56,11.0,98.75
2019-12-09,2.0,4.20,0.20,0.04,21.2,56.0,6.85,21.0,108.75
2019-11-18,2.0,7.10,0.20,0.13,23.3,110.0,6.89,75.0,360.00
2020-10-03,2.0,7.30,0.35,0.06,24.5,50.0,6.69,16.0,175.00
2020-11-17,5.0,8.70,0.18,0.10,31.4,50.0,7.20,24.0,975.00
2020-12-17,3.0,7.00,0.14,0.06,30.6,50.0,7.00,24.0,2750.00

In [11]:
q_turb = 67
q_fosf = 90
q_dbo = 97
q_ph = 80
q_res = 87
q_nit = 98
q_oxi = 5
q_turb = 58

In [17]:
soma_coli = 0
for i in _data["Coliformes"]:
    soma_coli += i
print(soma_coli/21)

soma_nit = 0
for i in _data["Nitrogenio"]:
    soma_nit += i
print(soma_nit/21)

soma_dbo = 0
    soma_dbo += i
print(soma_dbo/21)

soma_oxi = 0
for i in _data["Oxigenio"]:
    soma_oxi += i
print(soma_oxi/21)

soma_fos = 0
for i in _data["Fosforo"]:
    soma_fos += i
print(soma_fos/21)

soma_temp = 0
for i in _data["Temperatura"]:
    soma_temp += i
print(soma_temp/21)

soma_ph = 0
for i in _data["pH"]:
    soma_ph += i
print(soma_ph/21)

soma_turb = 0
for i in _data["Turbidez"]:
    soma_turb += i
print(soma_turb/21)

soma_res = 0
for i in _data["Residuos"]:
    soma_res += i
print(soma_res/21)

471.7261904761905
0.21809523809523806
2.1904761904761907
6.072380952380952
0.13809523809523808
24.509523809523806
6.835238095238095
21.885714285714286
63.904761904761905

In [12]:
# all_data = 

def IQA(data):
    IQA = 1
#     i = 0
    IQA_data = []
    w_list = [w_DBO, w_nitro, w_coli, w_pH, w_OD, w_temp, w_fosf, w_turb, w_res]
    for item in data["Valor"]:
        for w in w_list:
            IQA *= item**w
            IQA_data.append(IQA)
    return IQA_data

# data_IQA = IQA()